### ISSUE TITLE
Unknown "gc_draw" function

### ISSUE THREAD

**Issue by Zuhayer** [cmen/CMENGoogleChartsBundle#11]
When I run the example I get this error. Kindly let me know what am I missing?

`<script type="text/javascript">{{ gc_draw(piechart, 'div_chart') }}</script> `

**Comment by cmen** [comment]
Did you enable the bundle in your kernel ?

https://github.com/cmen/CMENGoogleChartsBundle/blob/master/Resources/doc/installation.md#step-2--enable-the-bundle

**Comment by Zuhayer** [comment]
Yes I did.

**Comment by cmen** [comment]
Example works for me with last version.
If you have more information to reproduce your bug...
