### ISSUE TITLE
Trendlines

### ISSUE THREAD

**Issue by liaram** [cmen/CMENGoogleChartsBundle#12]
Hi, 

Would it be possible to add trendlines?.
https://developers.google.com/chart/interactive/docs/gallery/trendlines

Thanks for advance.

**Comment by cmen** [comment]
Hi,

Trendlines are already implemented (see https://github.com/cmen/CMENGoogleChartsBundle/blob/master/GoogleCharts/Options/Trendlines.php). 
But this feature has never been tested and for the moment, there is no documentation.

So if you want to use this feature, you have to test on your side.
