### ISSUE TITLE
Dashboard feature

### ISSUE THREAD

**Issue by NCapiaumont** [cmen/CMENGoogleChartsBundle#13]
Bonjour,

Est il possible d'utiliser les fonctions dashboard de google ? (notamment les fonctionnalités de ChartRangeFilter).
https://developers.google.com/chart/interactive/docs/gallery/controls#chartrangefilter 
Je t'ai pas trouvé comment faire avec le bundle.

Merci

**Comment by cmen** [comment]
Bonjour,

Non, ce n'est pas disponible dans ce bundle.

**Comment by NCapiaumont** [comment]
Bonjour,

Ok dommage, merci de votre réponse 👍
