### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cristhianDt** [cmen/CMENGoogleChartsBundle#17]
Hi Guys,

First  thanks, this bundle is perfect to me and is very cool.

I want to ask you, is there a method of get the function name when I call "gc_draw"?, currently the function name is something like this "drawChart24b8756c043abd19abdd5ac1d94d5e97" in javascript, that value, I want it.

thanks,

**Comment by cmen** [comment]
Hi,

Currently, it is not possible to directly retrieve the generated function name (if someone wants to do a PR, I will merge it).

But you can calculate it in PHP or JS by taking inspiration from this line: https://github.com/cmen/CMENGoogleChartsBundle/blob/master/Output/Javascript/ChartOutput.php#L134
