### ISSUE TITLE
Rendering Chart in Bootstrap Tab

### ISSUE THREAD

**Issue by andrea-daru** [cmen/CMENGoogleChartsBundle#19]
I need to draw a chart in a tab that's not visible on load.
This situation lead to some graphical error (like worng text alignment)
![immagine](https://user-images.githubusercontent.com/8058905/41780129-311387ea-7634-11e8-8e4a-3e63294b3418.png)

Is there a way to redraw the chart on events?

**Comment by cyberJaw** [comment]
Try this:

`
//HTML
<div id="yearSales" class="chart"></div>

//CSS
.chart {
    width: 100%;
}
`

**Comment by cyberJaw** [comment]
This work fine.

`
//JS

{{ gc_draw([chart1],['chart1']) }}
    $("a[href='#tab1']").on('shown.bs.tab', function (e) {
        { gc_draw([chart1],['chart1]') }}
    });
    $("a[href='#tab2']").on('shown.bs.tab', function (e) {
        {{ gc_draw([chart2],['chart2]') }}
    });
`
