### ISSUE TITLE
Cant get PNG to work

### ISSUE THREAD

**Issue by darthf1** [cmen/CMENGoogleChartsBundle#2]
Hi. Great bundle! Makes it a lot more simpler to implement the Google Charts API.
I'm having an issue where i cannot get the print PNG function to work, as is described in the [readme](https://github.com/cmen/CMENGoogleChartsBundle/blob/master/Resources/doc/events.md).

Below is my code, I want to generate a PNG from an org structure, however the PNG DIV remains empty.

```
    <div id="div_chart"></div>
    <div id="png"></div>

    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
        {{ gc_start(orgchart, 'div_chart') }}

        {{ gc_event(orgchart, 'ready', 'printPng') }}

        function printPng() {
            document.getElementById('png').outerHTML = '<a href="' + {{ orgchart.name }}.getImageURI() + '">Printable version</a>';
        }

        {{ gc_end(orgchart) }}
    </script>
```

PHPStorm gives a semantic error on the ` {{ orgchart.name }}.getImageURI()` part: `This inspection reports expression statements which are not assignments or calls. Such statements have no dubious semantics, are normally the result of      programmer error.`

**Comment by cmen** [comment]
Hi !

getImageURI() is not available for Organization Chart. 
You can see available Javascript methods for this chart type here : https://developers.google.com/chart/interactive/docs/gallery/orgchart#methods
