### ISSUE TITLE
Toolbar option

### ISSUE THREAD

**Issue by jrobinsonadrenaline** [cmen/CMENGoogleChartsBundle#21]
I would categorize this as more of a question, rather than an issue, but does this bundle support the g charts toolbar option, [like this](https://developers.google.com/chart/interactive/docs/gallery/toolbar). If not it looks like I can use the gc_event extension to listen for the draw call and call the toolbar function. I just figured I would check with you first. Love this bundle so far, great work!

**Comment by christophe-jarvis** [comment]
Unfortunately, this bundle does not support the toolbar.
Yes, you can try to do this with events.
