### ISSUE TITLE
How to use calendar chart in Controller

### ISSUE THREAD

**Issue by khaliltr** [cmen/CMENGoogleChartsBundle#27]
I haven't understood the documentation official because they using javascript https://developers.google.com/chart/interactive/docs/gallery/calendar#a-simple-example,

I want to make it with php in symfony like the pieChart
 ```
       $pieChart = new PieChart();
        $pieChart->getData()->setArrayToDataTable(
            //data...
        ); ..

 i have used 

```
$calendar = new Calendar();
$calendar->getData()->setArrayToDataTable();.. 
```

but not working

**Comment by cmen** [comment]
Did you see and test the example here : https://github.com/cmen/CMENGoogleChartsBundle/blob/master/Resources/doc/cookbook.md#calendar-chart ?

**Comment by khaliltr** [comment]
Oh i'm sorry i didn't see that, thank you
