### ISSUE TITLE
Orgchart: root node is being ignored

### ISSUE THREAD

**Issue by darthf1** [cmen/CMENGoogleChartsBundle#3]
Hi. I'm trying to get an Org chart to display correctly and I've noticed a strange issue. My first node in the datatable, which is the root node, is always being ignored. The root node does not get rendered, however the root node is derived from the leaf node. 

Your example:
```
$org = new OrgChart();
$org->getData()->setArrayToDataTable(
    [
        [['v' => 'Mike', 'f' => 'Mike<div style="color:red; font-style:italic">President</div>'],
            '', 'The President'],
        [['v' => 'Jim', 'f' => 'Jim<div style="color:red; font-style:italic">Vice President</div>'],
            'Mike', 'VP'],
        ['Alice', 'Mike', ''],
        ['Bob', 'Jim', 'Bob Sponge'],
        ['Carol', 'Bob', '']
    ]
);
$org->getOptions()->setAllowHtml(true);
```

As a root node, i see 'Mike' without the 'President' text in red. If I remove the entire first line (```
 [['v' => 'Mike', 'f' => 'Mike<div style="color:red; font-style:italic">President</div>'],
            '', 'The President']```), from the datatable I still receive the same output. Which means the root node is ignored and is being derived from a leaf node, being Jim in this example.

If I would change 
```[['v' => 'Jim', 'f' => 'Jim<div style="color:red; font-style:italic">Vice President</div>'], 'Mike', 'VP']```
To 
```[['v' => 'Jim', 'f' => 'Jim<div style="color:red; font-style:italic">Vice President</div>'], 'Mikey', 'VP']```

The root node would display as "Mikey".

**Comment by cmen** [comment]
a937a14deaaa8edb14519f7a6f7b0c40858e02b1
