### ISSUE TITLE
Would you mind to store loader.js in the bundle?

### ISSUE THREAD

**Issue by stfalcon** [cmen/CMENGoogleChartsBundle#30]
It would be better for page speed

**Comment by cmen** [comment]
It is not allowed by Google : https://developers.google.com/chart/interactive/faq

> Can I use charts offline?
    Your users' computers must have access to https://www.gstatic.com/charts/loader.js in order to use the interactive features of Google Charts. This is because the visualization libraries that your page requires are loaded dynamically before you use them. The code for loading the appropriate library is part of the included script, and is called when you invoke the google.charts.load() method. Our terms of service do not allow you to download the google.charts.load or google.visualization code to use offline.

> Can I download and host the chart code locally, or on an intranet?
    Sorry; our terms of service do not allow you to download and save or host the google.charts.load or google.visualization code. However, if you don't need the interactivity of Google Charts, you can screenshot the charts and use them as you wish.
