### ISSUE TITLE
CalendarChart : "n.getFullYear is not a function error" with example datas

### ISSUE THREAD

**Issue by L0kidor** [cmen/CMENGoogleChartsBundle#32]
I, trying to setup a calendar chart.
I begin by copying pasting the [example provided in the doc](https://github.com/cmen/CMENGoogleChartsBundle/blob/master/Resources/doc/cookbook.md#calendar-chart) but not working. Got the error mentioned in the title.
Did I forget any include statement or whatever ?

**Comment by cmen** [comment]
This example works for me.
Did you include correctly the library in your template ?

```

**Comment by L0kidor** [comment]
I did, many other charts works fine.
My config : 

`cmen_google_charts:
    version: "current"
    language: "fr"`

And the template

`    <div id="div_chart"></div>
    
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        {{ gc_draw(statsAnnuelles, 'div_chart') }}
    </script>`

In my controller, i return that : 

`return $this->render('statistiques/annuelles.html.twig', array("statsAnnuelles" => $pieChart));`

**Comment by cmen** [comment]
Could you inspect the code with your browser and send me the generated Javascript for this chart ?

**Comment by L0kidor** [comment]
yep, here it is :

`
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

 <script type="text/javascript">
        google.charts.load('current', {packages:['calendar'], language: 'fr'});google.charts.setOnLoadCallback(drawChart0d56fd00ccdcb55add39726ee46112ad); function drawChart0d56fd00ccdcb55add39726ee46112ad() {var chartDiv_chart = new google.visualization.Calendar(document.getElementById("div_chart"));var dataChartDiv_chart = new google.visualization.arrayToDataTable([[{"label":"Date","type":"date"}, {"label":"Attendance","type":"number"}], [{"format":"2012-03-13","message":"This value is not a valid datetime.","payload":null}, 37032], [{"format":"2012-03-14","message":"This value is not a valid datetime.","payload":null}, 38024], [{"format":"2012-03-15","message":"This value is not a valid datetime.","payload":null}, 38024], [{"format":"2012-03-16","message":"This value is not a valid datetime.","payload":null}, 38108], [{"format":"2012-03-17","message":"This value is not a valid datetime.","payload":null}, 38229], [{"format":"2012-03-18","message":"This value is not a valid datetime.","payload":null}, 38177], [{"format":"2012-03-19","message":"This value is not a valid datetime.","payload":null}, 38705], [{"format":"2012-03-20","message":"This value is not a valid datetime.","payload":null}, 38210], [{"format":"2012-03-21","message":"This value is not a valid datetime.","payload":null}, 38029], [{"format":"2012-03-22","message":"This value is not a valid datetime.","payload":null}, 38823], [{"format":"2012-03-23","message":"This value is not a valid datetime.","payload":null}, 38345], [{"format":"2012-03-24","message":"This value is not a valid datetime.","payload":null}, 38436], [{"format":"2012-03-25","message":"This value is not a valid datetime.","payload":null}, 38447]], false);var optionsChartDiv_chart = {"calendar":{"cellColor":{"stroke":"#76a7fa","strokeOpacity":0.5,"strokeWidth":1},"cellSize":20,"dayOfWeekLabel":{"color":"#1a8763","fontName":"Times-Roman","fontSize":12,"bold":true,"italic":true},"dayOfWeekRightSpace":10,"daysOfWeek":"DLMMJVS","focusedCellColor":{"stroke":"#d3362d","strokeOpacity":1,"strokeWidth":1},"monthLabel":{"color":"#981b48","fontName":"Times-Roman","fontSize":12,"bold":true,"italic":true},"monthOutlineColor":{"stroke":"#981b48","strokeOpacity":0.8,"strokeWidth":2},"underMonthSpace":16,"underYearSpace":10,"unusedMonthOutlineColor":{"stroke":"#bc5679","strokeOpacity":0.8,"strokeWidth":1},"yearLabel":{"color":"#1A8763","fontName":"Times-Roman","fontSize":32,"bold":true,"italic":true}}, "height":350, "width":1000, "title":"Red Sox Attendance"};
chartDiv_chart.draw(dataChartDiv_chart, optionsChartDiv_chart);}
    </script>
`


The console doesn't show any error.

**Comment by cmen** [comment]
You have format errors for dates "This value is not a valid datetime.".

Here my version :
```js
google.visualization.arrayToDataTable([[{"label":"Date","type":"date"}, {"label":"Attendance","type":"number"}], 
[new Date(2012, 2, 13, 00, 00, 00), 37032], 
[new Date(2012, 2, 14, 00, 00, 00), 38024], 
[new Date(2012, 2, 15, 00, 00, 00), 38024], 
[new Date(2012, 2, 16, 00, 00, 00), 38108], 
[new Date(2012, 2, 17, 00, 00, 00), 38229], 
[new Date(2012, 2, 18, 00, 00, 00), 38177], 
[new Date(2012, 2, 19, 00, 00, 00), 38705], 
[new Date(2012, 2, 20, 00, 00, 00), 38210], 
[new Date(2012, 2, 21, 00, 00, 00), 38029], 
[new Date(2012, 2, 22, 00, 00, 00), 38823], 
[new Date(2012, 2, 23, 00, 00, 00), 38345], 
[new Date(2012, 2, 24, 00, 00, 00), 38436], 
[new Date(2012, 2, 25, 00, 00, 00), 38447]], false);
```

You should check date values passed into method **setArrayToDataTable**.

**Comment by L0kidor** [comment]
mhhh 

I used values[ mentionned here.](https://github.com/cmen/CMENGoogleChartsBundle/blob/master/Resources/doc/cookbook.md#calendar-chart)

I will try to change that.

**Comment by L0kidor** [comment]
Got it ! 

In the example the dates are passed like that : 
`[ new DateTime('2012-03-13'), 37032 ],`
wich is interprated as Symfony\Component\Validator\Constraints\DateTime.

Adding `\` before datetime make it interpreted as php dateTime:
`[ new \DateTime('2012-03-13'), 37032 ],`

And that works fine.

Thanks for supporting.

**Comment by cmen** [comment]
:+1:
