### ISSUE TITLE
Change Date Format

### ISSUE THREAD

**Issue by Chapier** [cmen/CMENGoogleChartsBundle#33]
Hello, 

First, Thank you for this package, 
Then : 
I don't know if I'm in the right place to ask this question.

How do you change the date format in LineChart ?
I would like to have "dd/mm/YYYY" and have years given 2 by 2.

Can I find somewhere all the options and possibility of this package ? Thank you

This is a sample of my data : 

array:19 [▼
  0 => array:2 [▼
    "order_number" => "188"
    "yearCreated" => "2001"
  ]
  1 => array:2 [▼
    "order_number" => "142"
    "yearCreated" => "2002"
  ]
  2 => array:2 [▼
    "order_number" => "109"
    "yearCreated" => "2003"
  ]
  3 => array:2 [▼
    "order_number" => "130"
    "yearCreated" => "2004"
  ]
  4 => array:2 [▼
    "order_number" => "155"
    "yearCreated" => "2005"
  ]
  5 => array:2 [▼
    "order_number" => "334"
    "yearCreated" => "2006"
  ]
  6 => array:2 [▼
    "order_number" => "487"
    "yearCreated" => "2007"
  ]
  7 => array:2 [▼
    "order_number" => "612"
    "yearCreated" => "2008"
  ]
  8 => array:2 [▼
    "order_number" => "336"
    "yearCreated" => "2009"
  ]
  9 => array:2 [▼
    "order_number" => "278"
    "yearCreated" => "2010"
  ]
  10 => array:2 [▼
    "order_number" => "259"
    "yearCreated" => "2011"
  ]
  11 => array:2 [▼
    "order_number" => "183"
    "yearCreated" => "2012"
  ]
  12 => array:2 [▼
    "order_number" => "148"
    "yearCreated" => "2013"
  ]
  13 => array:2 [▼
    "order_number" => "184"
    "yearCreated" => "2014"
  ]
  14 => array:2 [▼
    "order_number" => "152"
    "yearCreated" => "2015"
  ]
  15 => array:2 [▼
    "order_number" => "178"
    "yearCreated" => "2016"
  ]
  16 => array:2 [▼
    "order_number" => "117"
    "yearCreated" => "2017"
  ]
  17 => array:2 [▼
    "order_number" => "122"
    "yearCreated" => "2018"
  ]
  18 => array:2 [▼
    "order_number" => "50"
    "yearCreated" => "2019"
  ]
]

And I have only 2010 in the H-Axis...

**Comment by cmen** [comment]
Hello,

Instead of sending DateTime in method **setArrayToDataTable()** : 
```php
$chart = new LineChart();
$chart->getData()->setArrayToDataTable([
    ['Date', 'Sales', 'Expenses'],
    [new \DateTime('2017-01-01'),  1000,      400],
    [new \DateTume('2019-01-01'),  1170,      460],
    [...]
]);
```

You can directly send a formatted string date : 
```php
$chart = new LineChart();
$chart->getData()->setArrayToDataTable([
    ['Date', 'Sales', 'Expenses'],
    ['01/01/2017',  1000,      400],
    ['01/01/2019',  1170,      460],
    [...]
]);
```

**Comment by Chapier** [comment]
Perfect it's working.

In examples it's coded with a DateTime so i did the same.
But it's work better with only "string"

Thank you :)
