### ISSUE TITLE
How to change chart color of "Previous data" on Diff Charts?

### ISSUE THREAD

**Issue by manzolo** [cmen/CMENGoogleChartsBundle#34]
The default data color of "previous data" on diff charts is #eeeeee. 
With $chart->getOptions()->setColors(['#xxxxxx']); i can set colors of oldColumnChart and newColumnChart.
Is there a way to set color of diffColumnChart?
[https://github.com/cmen/CMENGoogleChartsBundle/blob/master/Resources/doc/diff_charts.md](url)

EDIT: 
I found this workaround:
                $('rect[fill="#eeeeee"]').each(function () {
                    $(this).attr("fill","#anothercolor");
                });
But i don't like it...

**Comment by cmen** [comment]
It seems it is not possible to configure "previous data". 
Nothing in Google documentation: https://developers.google.com/chart/interactive/docs/gallery/diffchart

Other people have the same problem: https://github.com/google/google-visualization-issues/issues/2552
