### ISSUE TITLE
Legend position "top / bottom" does not work for LineChart

### ISSUE THREAD

**Issue by Knallcharge** [cmen/CMENGoogleChartsBundle#40]
Hi,

when using the native JavaScript-implementation for GoogleCharts, "position: bottom" for a LineChart works fine, when using the bundle the legend is always right for position "top / bottom / right" or left for "left".
![2020-01-24 13_42_24](https://user-images.githubusercontent.com/1715912/73069987-79177200-3eaf-11ea-9f9e-6b7f97e46dfd.jpg)

**Comment by cmen** [comment]
Hi,

Do you use material line chart ? 
Legend position works only with "classic" line chart.

**Comment by Knallcharge** [comment]
You are right, thanks, my bad.
