### ISSUE TITLE
Can't edit position of legend...

### ISSUE THREAD

**Issue by bhyassine** [cmen/CMENGoogleChartsBundle#41]
Hello everyone,
I am trying to put the Legend in the center of my GeoChart, using:
`$geoChart->getOptions()->getLegend()->setPosition('center')`
but I have this Error:
`Attempted to call an undefined method named "setPosition" of class "CMEN\GoogleChartsBundle\GoogleCharts\Options\GeoChart\Legend".`
The Legend of GeoChart can't me moved?
Thanks for your help!

**Comment by cmen** [comment]
Hello,

https://developers.google.com/chart/interactive/docs/gallery/geochart#configuration-options

Only two options exists for GeoChart legend : numberFormat and textStyle
