### ISSUE TITLE
Material Line Charts Options

### ISSUE THREAD

**Issue by AmbroAnalog** [cmen/CMENGoogleChartsBundle#43]
I have problems setting up a material line chart because some options are not being applied.

For Example:
`$chart->getOptions()->setLineWidth(5);
$chart->getOptions()->setPointSize(10);
$chart->getOptions()->getVAxis()->setMinValue(0);`

None of the options shown above change anything about how my chart looks. Is this a known bug?
However, other settings for the same diagram such as the title will work.

I like to use your library very much and would appreciate help :)

**Comment by cmen** [comment]
Hello, sorry for the delay.

**Material** charts are in beta version. A lot of options does not work yet. You can read this [issue](https://github.com/google/google-visualization-issues/issues/2143).

It's better to use "classic" charts.
