### ISSUE TITLE
Mistake in the Documentation

### ISSUE THREAD

**Issue by yasirunilan** [cmen/CMENGoogleChartsBundle#6]
There is a slight mistake in the documentation under https://github.com/cmen/CMENGoogleChartsBundle/blob/HEAD/Resources/doc/basic_usage.md_usage.md  
Case 1 : One Chart the last line of the controller is missing a parenthesis.

![error](https://cloud.githubusercontent.com/assets/9814784/15902653/9d0cc65e-2dc6-11e6-939e-101f7c26ceed.PNG)

**Comment by cmen** [comment]
90bf1eb1e97ec2e88c3baebe8e1bdaa814fbb9c2
