### ISSUE TITLE
Allow the use of Material Design

### ISSUE THREAD

**Issue by numediaweb** [cmen/CMENGoogleChartsBundle#7]
Is it possible to reproduce the same result like this design?
http://jsfiddle.net/x8dafm9u/

Or by using:

```
var material = new google.charts.Bar(document.getElementById('chart_div'));
material.draw(data, options);
```

**Comment by cmen** [comment]
Materials charts are not available at the moment.

**Comment by cmen** [comment]
ab3b3561f21053ed2350ce04fd50d48a39c8b76a
