### ISSUE TITLE
Affichage courbes

### ISSUE THREAD

**Issue by falexis77** [cmen/CMENGoogleChartsBundle#8]
Hello,

Est ce que c'est possible d'afficher le graphique, avec deux courbes afin de montrer la différence de chiffres d'affaires entre deux entreprises , sur une période donnée par exemple ?

**Comment by cmen** [comment]
Salut,

Oui, c'est faisable sans problème avec les LineChart. On peut mettre un nombre infini de courbe avec en abscisse la période donnée.
